### PR TITLE
E10R-25

### PR DESCRIPTION
**Pull request by TomFlem**
At this point I am opening this PR for visibility more than anything else. I've commented out the SDK tests, as we don't ship it I am not sure we should care about testing it? Similarly I don't test the rulesengine on arm32 and arm64 as it seems to be unresponsive. 

I've ended up doing a few different things as part of this ticket:

- I've added a Jenkinsfile (and build https://jenkins.iotechsys.com/view/Blackbox%20Testing/job/blackbox-newman-build/) to build newman for x86, arm32 and arm64.
- I've removed some of the original Jenkinsfiles.
- I've parametrised the new Jenkinsfile/Jobs https://jenkins.iotechsys.com/view/Blackbox%20Testing/job/blackbox-go-x86_64/ (while it is possible to start the JAVA tests by setting the language parameter, I have not ensured they work - logic being we don't ship it so we don't care).
- Most of the issues I've had on the arm based architectures were to do with importing data into mongo before a set of tests run. I've made some changes/fixes to this process. 

I would argue that our tests should not use anything other than the APIs provided. If a device (etc) needs to be present for a test, it should be added via the API, not as a direct import into mongo. This should make the tests portable when another database is used. Thoughts?

I've had to adjust the arm64 mongo build to provide 'mongoimport'.

The results of the arm32 and arm64 tests can be viewed on these dashboards:
https://jenkins.iotechsys.com/view/EdgeXpert%20Testing%20(arm)/
https://jenkins.iotechsys.com/view/EdgeXpert%20Testing%20(arm64)/

### CODE REVIEW

**Comment by TomFlem** [comment]
Thanks for the changes Bruce. We still need to decide whether we are happy merging this stuff in? 

Especially given that I've commented out the SDK tests, and I don't test the rules engine on either arm architecture.

In the future it looks like we need a solution that is database agnostic, but at least with this work we have our tests running on multiple architectures.

**Comment by weichou1229** [comment]
You're right, I think this PR is done for https://iotechsys.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=E10R&modal=detail&selectedIssue=E10R-25  and can be merged. 
We can open other task for more dissccussion.
1.  rulesengine not work on 32bit arm
2. choose a solution for database agnostic

**Comment by TomFlem** [comment]
Sounds good, happy for me to merge this then?

**Comment by SteveOss** [comment]
From the database working group, for Dehli,  looks like will be adding a clean database abstraction
layer into the Go code and delivering a second database implementation using Redis. For portability all test scenarios should have test data populated via the standard service REST APIs.

**Pull request merged**
