### PR TITLE
Support logging

### PR DESCRIPTION
**Pull request by TomFlem**
Merge logging tests to master.

### CODE REVIEW

**Comment by weichou1229** [comment]
@TomFlem 
Why need
```
archiveArtifacts artifacts: 'bin/testResult/**.xml'
```
I think use ``junit 'bin/testResult/**.xml'`` is enough to record test result .

jenkins reference page https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/

**Comment by TomFlem** [comment]
I think I was experimenting with another job accessing the test results and amalgamating them. It could be removed if you think its a good idea?

**Comment by weichou1229** [comment]
what is the outcome when amalgamating them ?

**Comment by TomFlem** [comment]
I hoped to compare the results of the go and java test runs. However as the resulting xml files are basically identical, junit merges the results in an unhelpful way (you can't tell the go and java results apart). I've not found a better way of presenting the comparison so far. Can always remove the archive if you'd like?

**Comment by weichou1229** [comment]
I suggest  flush script can easy use ```db.collection.remove({});```
like https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/javascript/supportNotifications/flushScript.js
also you can see how import test in support-notification , I think it is more easy maintain

**Comment by weichou1229** [comment]
ok , I will discuss with @cloudxxx8 , is need some report to compare the results of the go and java test .

**Comment by weichou1229** [comment]
And I did not use data.json like ```bin/postman-test/data/loggingData.json```
cause it's just can be used in postman Runner or newman , not very convenient when I write test by Postman tool ,so I store in global variable .

**Comment by weichou1229** [comment]
about environment file , I separate two file
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/edgex.postman_environment.json
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/local_edgex.postman_environment.json

my purpose is make it more maintainable , can easy run test at local , you can reference the doc https://docs.google.com/document/d/1T-wnlx61hJc-BuqsJCs6Ve1ad1lUvkSXJ0ZwneQFYOI/edit?usp=sharing
I had write some script for local deploy and test .

**Comment by weichou1229** [comment]
@TomFlem 
compare java and go is ok , and I also not find a better way to do that , 
but we still can compare java and go by manual . 
so I think we can remove ```archiveArtifacts artifacts: 'bin/testResult/**.xml'``

**Comment by TomFlem** [comment]
> compare java and go is ok , and I also not find a better way to do that ,
but we still can compare java and go by manual .
so I think we can remove ```archiveArtifacts artifacts: 'bin/testResult/**.xml'``

Yep, I'll remove that from this PR.

**Comment by TomFlem** [comment]
> I suggest flush script can easy use db.collection.remove({});
like https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/javascript/supportNotifications/flushScript.js
also you can see how import test data in support-notification , I think it is more easy maintain

I can follow that structure instead, should the other be changed to remain consistent? I just followed the layout use by the other tests.

**Comment by TomFlem** [comment]
> And I did not use data.json like bin/postman-test/data/loggingData.json
cause it's just can be used in postman Runner or newman , not very convenient when I write test by Postman tool ,so I store in global variable .

I didn't have a problem using this and writing tests in postman. Isn't this the approach the other tests use?

**Comment by TomFlem** [comment]
> about environment file , I separate two file
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/edgex.postman_environment.json
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/local_edgex.postman_environment.json
my purpose is make it more maintainable , can easy run test at local , you can reference the doc https://docs.google.com/document/d/1T-wnlx61hJc-BuqsJCs6Ve1ad1lUvkSXJ0ZwneQFYOI/edit?usp=sharing
I had write some script for local deploy and test .

Does that mean:

https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/command.postman_environment.json
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/MetadataEnv.postman_environment.json
https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/CoredataEnv.postman_environment.json

are not used?

**Comment by weichou1229** [comment]
> I can follow that structure instead, should the other be changed to remain consistent? I just followed the layout use by the other tests.  

just change logging in this PR

> Does that mean:
> 
> https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/command.postman_environment.json
> https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/MetadataEnv.postman_environment.json
> https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/environment/CoredataEnv.postman_environment.json
> 
> are not used?

it's still used for other test suite , we can enhance these test next time

**Comment by weichou1229** [comment]
> > And I did not use data.json like bin/postman-test/data/loggingData.json
> > cause it's just can be used in postman Runner or newman , not very convenient when I write test by Postman tool ,so I store in global variable .
> > 
> 
> I didn't have a problem using this and writing tests in postman. Isn't this the approach the other tests use?
> 

oh, how can I pass the value to {{deviceDelRequestId}} , I didn't know how to import data.json in this view
image

**Comment by TomFlem** [comment]
> How to pass the {{deviceDelRequestId}} value? I didn't know how to import data.json in this view
image

I just have the runner open at the same time.

**Comment by TomFlem** [comment]
> I suggest flush script can easy use db.collection.remove({});
like https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/javascript/supportNotifications/flushScript.js
also you can see how import test data in support-notification , I think it is more easy maintain

Doesn't this just remove entire collections from mongo? That seems a bit unnecessary.

**Comment by weichou1229** [comment]
in my case , I want flush all test data ,and run
```
db. transmission.remove({});
db. notification.remove({});
db. subscription.remove({});
```
so , I don't need specific id like this https://github.com/IOTechSystems/postman-integration-test/blob/master/bin/postman-test/javascript/coredata/event.js

it's just more easy to flush test data

**Comment by TomFlem** [comment]
I've made a few changes:

- Archive step removed.
- I've fix the flush script but not changed it as I don't want to completely clear the collection and its functional as is.
- I've updated the testing to use the single environment file. The local version has been updated too.
- I have not changed the data file, it works and is consistent with the other tests. It could be changed in future along with those.

Any other comments?

**Comment by cloudxxx8** [comment]
> Archive step removed.
I agree with that.  We often run out of space.
> I've fix the flush script but not changed it as I don't want to completely clear the collection and its functional as is.
Sounds good.
> I've updated the testing to use the single environment file. The local version has been updated too.
Sounds good.
> I have not changed the data file, it works and is consistent with the other tests. It could be changed in future along with those.
Yes, the new style could be applied in the future.  Bruce just started using that.

I also start reviewing today.  I will sync with Bruce and should merge the code soon.

**Comment by cloudxxx8** [comment]
@TomFlem 

I saw lots of if statement in the test script, and some of them might not able to catch the bug.
For example, the following code can not catch the issue of response body is empty.  The empty body issue will be ignored by the if statement.
```
if(responseBody.length!== 0){",
"            tests[\"Body is correct\"] = responseBody === \"pong\";",
"        }"
```
Another example, as a designed test case, we could predict whether we have the reading data.  In this case, if the log is empty, the test should report fail
image

The same reason for the test about content-type.  If the API defines content-type, it must exist, or the fail should be reported
```
 if (contentTypeHeaderExists) {",
"        tests[\"Content-Type is application/json\"] =  responseHeaders[\"Content-Type\"].has(\"application/json\");",
```

**Comment by TomFlem** [comment]
@cloudxxx8 Yes I agree. I am away until next Tuesday. If you'd like to make changes feel free, otherwise I'll look at them when I return.

**Pull request merged**
